name: 'Frodo CLI Release Pipeline'

on:
  push:
    branches:
      - 'main'

jobs:
  homebrew-formula-update:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v2
        if: "!contains(github.ref, '-')" # skip prereleases
        with:
          formula-name: frodo-cli
          formula-path: Formula/frodo-cli.rb
          homebrew-tap: rockcarver/homebrew-frodo-cli
          download-url: https://github.com/rockcarver/frodo-cli.git
        env:
          COMMITTER_TOKEN: ${{ secrets.PAT_HOMEBREW_FORMULA_REPO }}
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
